### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by NotAmaan** [coana-tech/coana-issue-tracker#31]
For the last couple of days, Coana Package Manager seems to be stuck on loading on a project which is mono-repo.
It loads fine on a smaller project though.

I use zsh on MacOS (Sonoma)

The error I get is:
```
2023-09-30 03:27:18.067 [info] ExtensionService#_doActivateExtension Coana.coana-package-manager, startup: false, activationEvent: 'onView:coana.packages'
2023-09-30 03:27:18.128 [error] Activating extension Coana.coana-package-manager failed due to an error:
2023-09-30 03:27:18.128 [error] Error: Command failed: node -p "require.resolve('@cs-au-dk/jelly/lib/server')"
/bin/sh: node: command not found

	at checkExecSyncError (node:child_process:945:11)
	at execSync (node:child_process:1017:15)
	at node:electron/js2c/asar_bundle:2:12758
	at Wg.setupNewJellyProcess (/Users/*****/.vscode/extensions/coana.coana-package-manager-0.19.2/out/bundle/extension.js:123:11125)
	at new Wg (/Users/*****/.vscode/extensions/coana.coana-package-manager-0.19.2/out/bundle/extension.js:123:11042)
	at new NP (/Users/*****/.vscode/extensions/coana.coana-package-manager-0.19.2/out/bundle/extension.js:125:461)
	at GS (/Users/*****/.vscode/extensions/coana.coana-package-manager-0.19.2/out/bundle/extension.js:125:5131)
	at Object.<anonymous> (/Users/*****/.vscode/extensions/coana.coana-package-manager-0.19.2/out/bundle/extension.js:130:36219)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:135:5630)
	at m._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:132:29116)
	at D._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:19764)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:98)
	at n.rb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:132:30295)
	at async Promise.all (index 0)
```

**Comment by mtorp** [comment]
Hi @NotAmaan,

Thanks for reporting this.

It looks like it's unable to find Node.js when is required for executing the static analysis of the extension:
`2023-09-30 03:27:18.128 [error] Error: Command failed: node -p "require.resolve('@cs-au-dk/jelly/lib/server')"
/bin/sh: node: command not found`.

Can you check to see if Node.js is installed in your system and that it's available from VSCode, e.g., by running `node` in the VSCode terminal?

**Comment by NotAmaan** [comment]
Yeah I have node installed 
```
❯ node -v
v20.8.0
```

The default shell on MacOS is `zsh`, its what's configured in my vscode settings too
But for some reason, the extensions uses `/bin/sh`
Nevertheless, in my terminal, I double checked if node exists even in /bin/sh (it should if my paths are configured correctly)
```
❯ /bin/sh
sh-3.2$ node -v
v20.8.0
sh-3.2$ zsh
❯ node -v
v20.8.0
```

Searched for similar issues in other projects, this seemed similar:
https://github.com/formulahendry/vscode-code-runner/issues/355

This could explain why `/bin/sh` wasn't executing node, but I already have the symlink mention there 
https://github.com/realm/realm-js/issues/1448#issuecomment-340757479 

Issue could be specific to my OS/repo level configs, and I'm inclined towards that being the cause and closing this issue.

**Comment by NotAmaan** [comment]
Works fine in 0.19.3
